name: Validate CI with parameters in single file
on: [push, pull_request]

jobs:
  - build:
      name: Dotenv Action
      uses: falti/dotenv-action@v1.1.2
  - build: 
      name: Verify
      uses: apache/maven-gh-actions-shared/.github/workflows/maven-verify.yml@v4
       
        
            