name: Validate CI
on: [push, pull_request]

jobs:
  build:
    - name: Load environment variables
      uses: dotenv-actions/setup-dotenv@v2
      with:
        dotenv_path: .env
      run: echo "Host -> $API_KEY"