name: Validate CI
on: [push, pull_request]

jobs:
   build:
      name: dotenv
      uses: xom9ikk/dotenv@v2.3.0
    # - name: echo hello world
    #   run: echo "hello ${{ steps.dotenv.outputs.hello }}"