name: Validate CI with separate parameters
on: [push, pull_request]

jobs:
  build:
    name: Verify
    uses: apache/maven-gh-actions-shared/.github/workflows/maven-verify.yml@v4
    with:
      maven-matrix: ${{ vars.matrix-parameters.maven-matrix }}
      jdk-matrix: ${{ vars.matrix-parameters.jdk-matrix }}
      os-matrix: ${{ vars.matrix-parameters.os-matrix }}