name: Validate CI
on: [push, pull_request]

jobs:
  load-config:
    runs-on: ubuntu-latest
    outputs:
      maven_matrix: ${{ steps.load_config.outputs.maven_matrix }}
      jdk_matrix: ${{ steps.load_config.outputs.jdk_matrix }}
      os_matrix: ${{ steps.load_config.outputs.os_matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Load config values
        id: load_config
        run: |
          import yaml
          with open("./src/build_options.yml", "r") as stream:
              config = yaml.safe_load(stream)
          print(f"::set-output name=maven_matrix::{config['maven-matrix']}")
          print(f"::set-output name=jdk_matrix::{config['jdk-matrix']}")
          print(f"::set-output name=os_matrix::{config['os-matrix']}")
        shell: python

  build:
    name: Verify
    needs: load-config
    uses: apache/maven-gh-actions-shared/.github/workflows/maven-verify.yml@v4
    with:
      maven-matrix: ${{ needs.load-config.outputs.maven_matrix }}
      jdk-matrix: ${{ needs.load-config.outputs.jdk_matrix }}
      os-matrix: ${{ needs.load-config.outputs.os_matrix }}
